export const ADD_TO_CTN = 'ADD_TO_CTN'
export const ADD_COMP = 'ADD_COMP'
export const EDIT_COMP = 'EDIT_COMP'
export const SET_CUR_COMP = 'SET_CUR_COMP'
export const SET_CUR_PAGE_INDEX = 'SET_CUR_PAGE_INDEX'
